### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by opensourcecompany** [bigbluebutton/bbb-install#56] opened 2019-07-09 11:59 UTC
When using the actual version, the installation fails at installing tomcat:

`Setting up tomcat7 (7.0.68-1ubuntu0.4) ...

Creating config file /etc/default/tomcat7 with new version
Adding system user `tomcat7' (UID 112) ...
Adding new user `tomcat7' (UID 112) with group `tomcat7' ...
Not creating home directory `/usr/share/tomcat7'.

Creating config file /etc/logrotate.d/tomcat7 with new version
Job for tomcat7.service failed because the control process exited with error code. See "systemctl status tomcat7.service" and "journalctl -xe" for details.
invoke-rc.d: initscript tomcat7, action "start" failed.
● tomcat7.service - LSB: Start Tomcat.
   Loaded: loaded (/etc/init.d/tomcat7; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-07-09 13:48:57 CEST; 17ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 30952 ExecStart=/etc/init.d/tomcat7 start (code=exited, status=1/FAILURE)

Jul 09 13:48:52 bbb systemd[1]: Starting LSB: Start Tomcat....
Jul 09 13:48:52 bbb tomcat7[30952]:  * Starting Tomcat servlet engine tomcat7
Jul 09 13:48:52 bbb su[30969]: Successful su for tomcat7 by root
Jul 09 13:48:52 bbb su[30969]: + ??? root:tomcat7
Jul 09 13:48:52 bbb su[30969]: pam_unix(su:session): session opened for user tomcat7 by (uid=0)
Jul 09 13:48:57 bbb tomcat7[30952]:    ...fail!
Jul 09 13:48:57 bbb systemd[1]: tomcat7.service: Control process exited, code=exited status=1
Jul 09 13:48:57 bbb systemd[1]: Failed to start LSB: Start Tomcat..
Jul 09 13:48:57 bbb systemd[1]: tomcat7.service: Unit entered failed state.
Jul 09 13:48:57 bbb systemd[1]: tomcat7.service: Failed with result 'exit-code'.
dpkg: error processing package tomcat7 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-demo:
 bbb-demo depends on tomcat7; however:
  Package tomcat7 is not configured yet.

dpkg: error processing package bbb-demo (--configure):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19.1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Processing triggers for systemd (229-4ubuntu21.22) ...
Errors were encountered while processing:
 tomcat7
 bbb-demo
E: Sub-process /usr/bin/dpkg returned an error code (1)
+ '[' '!' -f /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp ']'
+ sleep 1
+ echo -n .
`

**Comment by ffdixon** [comment] 2019-07-09 13:27
Hi there,

  * What version of BigBlueButton are you trying to install? 
  * Are you installing manually or using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install)?

If you are installing manually, can you try using `bbb-install.sh` and let us know if that gets you going.

**Comment by opensourcecompany** [comment] 2019-07-09 13:34
Hi :-)

Latest, 2.2 beta.
Fresh Ubuntu 16.04 server.
Using bbb-install.sh with predefined hostname, mail address and turn server.

Problem seems to be bbb-demo, there might be some dependencies which are not solved in the right order or maybe some semantic stuff that blocks tomcat7 from starting.

After completely deleting all references to bbb-demo the installation went well.

**Comment by ffdixon** [comment] 2019-07-09 13:41
Hmm ... the error was from an install of tomcat7, and we don't see this error when setting up our test servers. 

Glad you got it working.  Is there anything different about the server (locale, etc.) that you could share that might help us reproduce the issue.

**Comment by opensourcecompany** [comment] 2019-07-09 13:58
Okay... after a simple restart, tomcat refuses to start.
Finally i have an error in the logfile:

`-Djava.endorsed.dirs=/usr/share/tomcat7/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

So, this seems to be a tomcat/java bug. Reproduceable, installed this on several machines just to see if it might be a hardware issue.
Currently debugging, will keep you updated.

**Comment by opensourcecompany** [comment] 2019-07-09 14:45
This looks somewhat the same as here: [google groups](https://groups.google.com/forum/#!topic/bigbluebutton-dev/soDbmVUW2ZQ)

Executed the touch command, but how should this solve an issue...?
I can reproduce this in all my newly setup instances, there is the bbb-demo war missing...?

**Comment by ffdixon** [comment] 2019-07-09 16:45
Hmm ... what version of the JRE are you running?

~~~
# dpkg -l | grep jre
ii  default-jre                           2:1.8-56ubuntu2                                 amd64        Standard Java or Java compatible Runtime
ii  default-jre-headless                  2:1.8-56ubuntu2                                 amd64        Standard Java or Java compatible Runtime (headless)
ii  openjdk-8-jre:amd64                   8u212-b03-0ubuntu1.16.04.1                      amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64          8u212-b03-0ubuntu1.16.04.1                      amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
~~~

**Comment by elacunza** [comment] 2019-07-12 11:45
I can reproduce this problem, tryied 3 times to install from scratch :-)
Problem seem to be that currently default jre is v9:
# dpkg -l|grep jre
ii  openjdk-8-jre-headless:amd64          8u212-b03-0ubuntu1.16.04.1                 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-9-jre-headless:amd64          9~b114-0ubuntu1                            amd64        OpenJDK Java runtime, using Hotspot JIT (headless)

It seems to be fixed by:
# apt-get install default-jre
At least tomcat7 and bbb-demo packages complete their installation.

**Comment by davidrojo** [comment] 2019-07-12 13:39
Same problem here. Fresh install with bbb-setup.sh on ubuntu 16.04.

```
Creating config file /etc/logrotate.d/tomcat7 with new version
Job for tomcat7.service failed because the control process exited with error code. See "systemctl status tomcat7.service" and "journalctl -xe" for details.
invoke-rc.d: initscript tomcat7, action "start" failed.
● tomcat7.service - LSB: Start Tomcat.
   Loaded: loaded (/etc/init.d/tomcat7; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-07-12 15:11:51 CEST; 8ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 31793 ExecStart=/etc/init.d/tomcat7 start (code=exited, status=1/FAILURE)

Jul 12 15:11:45 bbb2 systemd[1]: Starting LSB: Start Tomcat....
Jul 12 15:11:45 bbb2 tomcat7[31793]:  * Starting Tomcat servlet engine tomcat7
Jul 12 15:11:45 bbb2 su[31810]: Successful su for tomcat7 by root
Jul 12 15:11:45 bbb2 su[31810]: + ??? root:tomcat7
Jul 12 15:11:46 bbb2 su[31810]: pam_unix(su:session): session opened for user tomcat7 by (uid=0)
Jul 12 15:11:51 bbb2 tomcat7[31793]:    ...fail!
Jul 12 15:11:51 bbb2 systemd[1]: tomcat7.service: Control process exited, code=exited status=1
Jul 12 15:11:51 bbb2 systemd[1]: Failed to start LSB: Start Tomcat..
Jul 12 15:11:51 bbb2 systemd[1]: tomcat7.service: Unit entered failed state.
Jul 12 15:11:51 bbb2 systemd[1]: tomcat7.service: Failed with result 'exit-code'.
dpkg: error processing package tomcat7 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-demo:
 bbb-demo depends on tomcat7; however:
  Package tomcat7 is not configured yet.

dpkg: error processing package bbb-demo (--configure):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-19.1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Processing triggers for systemd (229-4ubuntu21.22) ...
Errors were encountered while processing:
 tomcat7
 bbb-demo
E: Sub-process /usr/bin/dpkg returned an error code (1)
+ '[' '!' -f /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp ']'
+ sleep 1
```

```
# dpkg -l | grep jre
ii  openjdk-8-jre-headless:amd64          8u212-b03-0ubuntu1.16.04.1                 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-9-jre-headless:amd64          9~b114-0ubuntu1                            amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```

I've tried @elacunza solution and after that I've executed again bbb-install and now it works

```
# apt-get install default-jre
# systemctl status tomcat7.service
● tomcat7.service - LSB: Start Tomcat.
   Loaded: loaded (/etc/init.d/tomcat7; bad; vendor preset: enabled)
   Active: active (running) since Fri 2019-07-12 15:31:25 CEST; 5s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 366 ExecStart=/etc/init.d/tomcat7 start (code=exited, status=0/SUCCESS)
    Tasks: 23
   Memory: 95.5M
      CPU: 3.691s
   CGroup: /system.slice/tomcat7.service
           └─395 /usr/lib/jvm/default-java/bin/java -Djava.util.logging.config.file=/var/lib/tomcat7/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.

Jul 12 15:31:20 bbb2 systemd[1]: Starting LSB: Start Tomcat....
Jul 12 15:31:20 bbb2 tomcat7[366]:  * Starting Tomcat servlet engine tomcat7
Jul 12 15:31:25 bbb2 tomcat7[366]:    ...done.
Jul 12 15:31:25 bbb2 systemd[1]: Started LSB: Start Tomcat..
```

**Comment by tobiasgoecke** [comment] 2019-07-14 13:18
+1

**Comment by muzo178** [comment] 2019-07-26 08:18
> I can reproduce this problem, tryied 3 times to install from scratch :-)
> Problem seem to be that currently default jre is v9:
> 
> # dpkg -l|grep jre
> ii openjdk-8-jre-headless:amd64 8u212-b03-0ubuntu1.16.04.1 amd64 OpenJDK Java runtime, using Hotspot JIT (headless)
> ii openjdk-9-jre-headless:amd64 9~b114-0ubuntu1 amd64 OpenJDK Java runtime, using Hotspot JIT (headless)
> 
> It seems to be fixed by:
> 
> # apt-get install default-jre
> At least tomcat7 and bbb-demo packages complete their installation.

i had the same problem... this worked for me.

**Comment by ffdixon** [comment] 2019-07-27 12:53
I think the solution is to add installation of `default-jre` to `bbb-install.sh`.  What is funny is this issue doesn't always appear in our testing.

For folks in this thread, are you encountering this issue on a particular VPS provider?

**Comment by muzo178** [comment] 2019-07-27 15:19
> I think the solution is to add installation of `default-jre` to `bbb-install.sh`. What is funny is this issue doesn't always appear in our testing.
> 
> For folks in this thread, are you encountering this issue on a particular VPS provider?

I ran into this issue on a Hetzner Cloud instance.

**Comment by davidrojo** [comment] 2019-07-27 22:55
@ffdixon I ran also in hetzner cloud.

**Comment by elacunza** [comment] 2019-08-01 06:16
Hetzner cloud too :)

**Comment by ffdixon** [comment] 2019-08-01 11:48
We updated `bbb-install.sh` with and installed `default-jre` before other components.  It's also listed as a dependency on other BigBlueButton packages.  Could you try installing on Hetzner with this new version of `bbb-install.sh` and let us know if you still encounter the problem.  Thanks!

  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L184

**Comment by elacunza** [comment] 2019-09-30 11:09
I just built a test server with the new script, it works well.

Thanks a lot (and sorry for the delay getting back)

**Comment by davidrojo** [comment] 2019-10-29 08:57
Hi, I can confirm that the bug is fixed. I've done a fresh install on hetzner server and works fine.

**Comment by ffdixon** [comment] 2019-10-29 09:51
Thanks for letting us know.

**Closed by ffdixon** 2019-10-29 09:51 UTC

**Comment by dangngocbinh** [comment] 2020-02-16 09:24
Please try this:

Edit "/etc/default/tomcat7" and uncomment and change JAVA_HOME like this.

JAVA_HOME=/usr/lib/jvm/java-8-oracle
Now, start Tomcat7 service by this command.

sudo service tomcat7 start

I work for me!
ref: https://www.djamware.com/post/588df76680aca722878a364a/install-nginx-tomcat-7-and-java-8-on-ubuntu-1604#install-tomcat

**Comment by andrem1987** [comment] 2020-04-24 11:00
I ran into the same problem while installing BBB on a Hetzner server. Could you please edit the "Manual Install" instructions as well? That would have saved me an hour of tinkering ;-)

**Comment by lonesomewalker** [comment] 2020-04-24 11:37
At the moment, there is no need to edit some stuff.
bbb-install.sh works out-of-the-box.
Tested on more than 500 boxes at Hetzner.

**Comment by andrem1987** [comment] 2020-04-24 13:59
I am not talking about the bbb-install.sh script, but about the manual "Step-by-Step" Installation guide where this step is missing or should be mentioned at least.

**Comment by lonesomewalker** [comment] 2020-04-24 22:33
Then please post it where it belongs, not here for the bbb-install ;-)
