### ISSUE TITLE
bbb-webhooks - inactive `unsafe-perm` is not a valid npm option

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bbb-install#682] opened 2023-09-13 10:32 UTC
Hello, I updated from version 2.6.11 to 2.7, when doing "sudo bbb-conf --status" the bbb-webhooks process did not start, what it shows is:
npm ERR! `unsafe-perm` is not a valid npm option
and the log file shows the following:

"0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.7
2 info using node@v18.17.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/usr/local/bigbluebutton/bbb-webhooks/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/root/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 7ms
17 timing npm:load:configload Completed in 7ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm config set unsafe-perm true
21 verbose argv "config" "set" "unsafe-perm" "true"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-09-12T04_32_57_200Z-
26 verbose logfile /root/.npm/_logs/2023-09-12T04_32_57_200Z-debug-0.log
27 timing npm:load:logFile Completed in 7ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 20ms
31 info config set "unsafe-perm" "true"
32 timing command:config Completed in 1ms
33 verbose stack Error: `unsafe-perm` is not a valid npm option
33 verbose stack     at Config.set (/usr/lib/node_modules/npm/lib/commands/config.js:158:15)
33 verbose stack     at Config.exec (/usr/lib/node_modules/npm/lib/commands/config.js:120:22)
33 verbose stack     at Config.cmdExec (/usr/lib/node_modules/npm/lib/base-command.js:130:17)
33 verbose stack     at Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:168:20)
33 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:89:5)
34 verbose cwd /usr/local/bigbluebutton/bbb-webhooks
35 verbose Linux 5.15.0-1044-aws
36 verbose node v18.17.1
37 verbose npm  v9.6.7
38 error `unsafe-perm` is not a valid npm option
39 verbose exit 1
40 timing npm Completed in 36ms
41 verbose code 1
42 error A complete log of this run can be found in: /root/.npm/_logs/2023-09-12T04_32_57_200Z-debug-0.log
"
when manually starting the process
sudo service bbb-webhooks start
booted correctly

BBB version:
bbb 2.6.12
Ubuntu 20.04 64-bit in aws EC2 instance c6a.xlarge

Desktop (please complete the following information):

    OS: Windows 11
    Browser Firefox 117.0 (64-bit)

**Comment by ffdixon** [comment] 2023-09-13 10:51
The fix should be in 2.7.1.  See https://github.com/bigbluebutton/bigbluebutton/issues/18734#issuecomment-1714104616

**Comment by ffdixon** [comment] 2023-09-13 10:51
Duplicate of #18734.

**Closed by ffdixon** 2023-09-13 10:51 UTC
